version: "3.9"

networks:
  app_net:
    driver: bridge

services:
  db:
    image: postgres:18.1
    container_name: postgres-db-django
    restart: always
    ports:
      - "5222:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${VOLUME_POSTGRES}
    networks:
      - app_net

  api:
    image: avalentyn/django-api:latest
    container_name: django-api
    restart: always
    volumes:
      - ${VOLUME_SERVER_API}
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_PORT: 5222
    ports:
      - "4512:8000"
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    networks:
      - app_net

  front:
    image: avalentyn/my-post:latest
    container_name: my-post-front
    restart: always
    depends_on:
      - api
    ports:
      - "4513:80"
    networks:
      - app_net