version: "3.9"

services:
  api:
    image: avalentyn/django-api:latest
    container_name: django-api
    ports:
      - "4512:8000"
  front:
    image: avalentyn/my-post:latest
    #build: 
    #  context: ./my-transfer-ts
    container_name: my-post-front
    ports:
      - "4513:80"