# Generated by Django 6.0.3 on 2026-04-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='city',
            table='tblCities',
        ),
    ]
